# CrackSeg Environment - PyTorch 2.7 Focused & Minimal
# Strategy: Specify only CRITICAL versions, let conda resolve the rest
# Priority: Latest PyTorch > GUI stability
# Hardware: RTX 3070 Ti Laptop (8GB VRAM, 5888 CUDA Cores)

name: crackseg
channels:
  - conda-forge        # PRIMARY CHANNEL (post PyTorch deprecation)
  - nvidia             # CUDA Toolkit
  - defaults

dependencies:
  # 🚀 CRITICAL CORE (Exact versions)
  - python=3.12
  - pytorch=2.7          # LATEST STABLE - Core priority
  - cuda-toolkit=12.9    # RTX 3070 Ti optimization

  # 📊 ESSENTIAL ML STACK (Flexible ranges)
  - numpy                # Latest stable with performance improvements
  - opencv               # Computer vision
  - scikit-learn         # Classical ML
  - pandas               # Data manipulation
  - matplotlib           # Basic plotting + architecture visualization

  # 🏗️ COMPUTER VISION MODELS (conda-forge prioritized)
  - timm                 # Swin Transformer models (replaces torchvision.models)
  - albumentations       # Image augmentations (replaces torchvision.transforms)
  - segmentation-models-pytorch  # Pre-trained segmentation models

  # 🧪 DEVELOPMENT & TESTING
  - pytest               # Testing framework
  - black                # Code formatting
  - ruff                 # Fast linting
  - basedpyright         # Static type checking
  - coverage             # Code coverage
  - selenium             # Web browser automation for E2E testing

  # 📊 DATA FORMATS & PROCESSING
  - pillow               # Image processing
  - h5py                 # HDF5 support
  - scipy                # Scientific computing
  - scikit-image         # Image processing algorithms

  # 📈 DATA ANALYSIS & VISUALIZATION
  - seaborn              # Statistical data visualization
  - plotly               # Interactive plotting for advanced visualizations
  - tqdm                 # Progress bars

  # 🔧 MODEL UTILITIES & MONITORING
  - tensorboard          # TensorBoard for monitoring

  # ⚙️ SYSTEM & UTILITIES
  - psutil               # System and process utilities
  - pyyaml               # YAML parser
  - toml                 # TOML parser
  - click                # Command line interface creation
  - requests             # HTTP library
  - python-dotenv        # .env file support for environment variables
  # Note: pynvml not included - optional GPU monitoring with graceful fallback
  # Install manually if advanced GPU monitoring is needed: conda install pynvml
  # - graphviz             # REMOVED: ADR-001 - Replaced with matplotlib for architecture visualization
  #                        # Reason: gdk-pixbuf compilation issues on Windows with PyTorch 2.7
  #                        # Alternative: matplotlib-based rendering in src/model/common/utils.py
  #                        # Reference: docs/guides/architectural_decisions.md#adr-001

  # 🎨 GUI & CONFIGURATION (TEMPORARILY REDUCED)
  # - streamlit            # TEMPORARILY DISABLED - GUI issues on Windows
  - hydra-core           # Configuration management framework
  - omegaconf            # Configuration system

  # 📦 PIP FALLBACK (ONLY if not available in conda)
  - pip

  - pip:
    # Streamlit installed via pip to avoid gdk-pixbuf issues
    - streamlit
    # GUI components not available in conda channels
    - streamlit-ace       # Ace editor for YAML editing
    # Plotly image export support
    - kaleido             # Static image export for Plotly (PNG, PDF, SVG)
    # Currently empty - all packages moved to conda!
    # This section is kept for future pip-only dependencies

# ENVIRONMENT VARIABLES
variables:
  NO_ALBUMENTATIONS_UPDATE: 1
  CUDA_VISIBLE_DEVICES: 0