# @package _group_

# Configuration for the mock bottleneck used in tests
type: TestBottleneck  # Registered name in bottleneck_registry
in_channels: 64      # Must match output of mock encoder
# No _target_ needed as factory uses 'type' 