# @package _group_

# Default decoder configuration - using mock for now
_target_: src.model.decoder.cnn_decoder.CNNDecoder

# in_channels will be set by the model factory based on bottleneck output
# skip_channels_list will be set by the model factory based on encoder output
# out_channels is typically for the number of segmentation classes (e.g., 1 for binary)

out_channels: 1 # Example for binary segmentation
# depth can be inferred from skip_channels_list by the factory if not set
# target_size can be set if a specific output H, W is needed, else inferred

# Parameters now part of CNNDecoderConfig
config:
  upsample_scale_factor: 2
  upsample_mode: "bilinear"
  kernel_size: 3
  padding: 1
  use_cbam: false # Or true if CBAM is desired
  cbam_reduction: 16