# @package _group_

# Configuration for the mock decoder used in tests
# Used for testing model assembly and integration

type: TestDecoder        # Registered name in decoder_registry (mock/test decoder)
in_channels: 128         # Number of input channels (must match output of mock bottleneck)
skip_channels: [16, 32]  # Skip connection channels (must match skip_channels of mock encoder)
out_channels: 1          # Number of output channels (mock decoder property returns 1)
# No _target_ needed as factory uses 'type' 