# configs/training/logging/logging_base.yaml

# Base configuration for logging during training and evaluation

# Enable or disable logging entirely
enabled: true

# Type of logger to use. Options: [tensorboard, wandb, mlflow, none]
# If 'none' or null, NoOpLogger will be used.
type: tensorboard

# Base directory for logger outputs (relative to Hydra's run directory)
# Specific loggers might create subdirectories within this.
log_dir: "${hydra.run.dir}/logs/${logging.type}/" # Example: outputs/.../logs/tensorboard/

# Frequency of logging (to be interpreted by the Trainer)
log_interval_batches: 50 # Log every N batches (0 to disable batch logging)
log_epoch_metrics: true  # Log aggregated metrics at the end of each epoch

# Metrics to log (if empty or null, log all available)
# Example: [train_loss, val_loss, val_iou, val_f1]
metrics_to_log: null

# --- Visualization Settings (Specific to logger type) ---
visualization:
  enabled: true # Enable/disable visualization generation (e.g., saving plots)
  # Metrics to visualize (e.g., generating plots for)
  # Example: [loss_curves, val_iou_trend]
  visualize_metrics: [loss_curves]
  # Add other viz parameters as needed

# --- TensorBoard Specific Settings (only used if type is tensorboard) ---
tensorboard:
  # Add specific TensorBoard settings here if needed in the future
  # Example: flush_secs: 120, filename_suffix: ""
  pass # Placeholder

# --- WandB Specific Settings (only used if type is wandb) ---
wandb:
  project: "crack_segmentation" # Default project name
  entity: null # Your WandB entity (username or team)
  log_model: false # Whether to log model checkpoints to WandB
  # Add other WandB settings
  pass # Placeholder

# --- MLflow Specific Settings (only used if type is mlflow) ---
mlflow:
  # Add MLflow settings like tracking_uri, experiment_name etc.
  pass # Placeholder 