# =============================================================================
# Centralized configuration for linting tools in the CrackSeg project
# =============================================================================

# Config file paths
config_files:
  black: "${project_root}/pyproject.toml"
  ruff: "${project_root}/pyproject.toml"
  basedpyright: "${project_root}/pyproject.toml"
  pre_commit: "${project_root}/.git/hooks/pre-commit"

# Linting tools
tools:
  # Black for automatic code formatting
  black:
    version_required: ">=23.3.0"
    command: "black"
    docs_url: "https://black.readthedocs.io/en/stable/"
    config_section: "tool.black"

  # Ruff for linting and style
  ruff:
    version_required: ">=0.4.0"
    command: "ruff"
    docs_url: "https://docs.astral.sh/ruff/"
    config_section: "tool.ruff"

  # Basedpyright for static type checking
  basedpyright:
    version_required: ">=1.0.0"
    command: "basedpyright"
    docs_url: "https://github.com/DetachHead/basedpyright"
    config_section: "tool.basedpyright"

# Improvement plan (example, update as needed)
improvement_plan:
  phases:
    format:
      description: "Formatting issues"
      duration_weeks: 2
      tools: ["black"]
    lint:
      description: "Linting and style issues"
      duration_weeks: 3
      tools: ["ruff"]
    typing:
      description: "Type checking issues"
      duration_weeks: 2
      tools: ["basedpyright"]

# Scripts available
scripts:
  # No unified lint_manager, use tools directly via pre-commit or CLI
  # Example usage:
  #   black .
  #   ruff .
  #   basedpyright .