# @package model

# Base UNet configuration schema

_target_: src.model.core.unet.BaseUNet

# --- Component Configurations ---
# These sections define the expected structure for each component.
# Using the correct class names as sugeridos por los mensajes de error

encoder:
  # Use the correct encoder class name
  _target_: src.model.encoder.CNNEncoder
  in_channels: 3

bottleneck:
  # Use the correct bottleneck class name
  _target_: src.model.bottleneck.BottleneckBlock
  in_channels: 512 # Ajustar según el encoder
  out_channels: 1024 # Ajustar según la arquitectura

decoder:
  # Use the correct decoder class name
  _target_: src.model.decoder.CNNDecoder
  in_channels: 1024 # Debe coincidir con out_channels del bottleneck
  skip_channels_list: [512, 256, 128, 64] # Orden invertido respecto al encoder
  out_channels: 1 # Número de clases de salida
  depth: 4 # Profundidad del decoder, igual que encoder

# --- Optional Final Activation ---
final_activation: null
# Example:
# final_activation:
#   _target_: torch.nn.Sigmoid 