# @package _global_

# Configuration for a UNet using mock components for testing

# Inherit base structure and override components
ddefaults:
  - model: default  # Inherit base UNet schema (_target_, type, final_activation)
  - _self_

# Override component sections with mock configurations
model:
  # Use the actual BaseUNet implementation as the target
  _target_: src.model.unet.BaseUNet
  # type: BaseUNet  # Type is less relevant if using _target_ directly

  encoder:
    in_channels: 3
    _target_: tests.model.unit.test_registry.MockEncoder

  bottleneck:
    in_channels: 64  # Matches MockEncoder output
    _target_: tests.model.unit.test_registry.MockBottleneck

  decoder:
    in_channels: 128  # Matches MockBottleneck output
    # Usamos [16, 32] que es lo que espera el test de integración
    # MockDecoder.skip_channels_expected() retorna [32, 16], pero eso es el RESULTADO
    # de la inversión, no lo que debe recibir.
    skip_channels_list: [16, 32]
    _target_: tests.model.unit.test_registry.MockDecoder

  # Optional: Override final activation
  final_activation:
    _target_: torch.nn.Sigmoid

# Specific UNet configuration (can override defaults if needed)
# type: TestUNet  # Optional: If TestUNet was registered in unet_registry

# Example override: Add final activation
final_activation:
  _target_: torch.nn.Sigmoid 