import csv

# ruff: noqa: E501
CSV_PATH = "outputs/prd_project_refinement/test_suite_evaluation/reports/test_inventory.csv"
SLOW_TESTS_PATH = "outputs/prd_project_refinement/test_suite_evaluation/reports/slow_tests.txt"

# Palabras clave para asignar prioridad
CRITICAL_KEYWORDS = [
    "pipeline",
    "training_loop",
    "evaluate",
    "ensemble",
    "end_to_end",
    "integration",
    "trainer",
    "main",
    "forward_pass",
    "full_unet_data_flow",
    "data_pipeline",
    "train",
    "eval",
    "checkpoint_resume",
    "aspp",
    "cnn_convlstm_unet",
    "swin_transformer",
    "unet",
    "BaseUNet",
    "SimpleConvLSTMBottleneck",
]
HIGH_KEYWORDS = [
    "model",
    "encoder",
    "decoder",
    "bottleneck",
    "cbam",
    "loss",
    "metrics",
    "factory",
    "registry",
    "config",
    "dataloader",
    "dataset",
    "sampler",
    "memory",
    "logging",
    "early_stopping",
    "split",
    "override",
    "schema",
    "exports",
    "component",
    "hybrid",
    "import_compat",
    "reproducibility",
    "precision",
    "recall",
    "f1_score",
    "iou_score",
    "visualize",
    "save",
    "load",
    "checkpoint",
    "activation",
    "optimizer",
    "scheduler",
    "batch",
    "epoch",
    "summary",
    "grad",
    "dropout",
    "skip_connection",
    "channel",
    "init",
    "init_type_mismatch",
    "init_with_activation",
    "forward_shape",
    "output_shape",
    "output_norm",
    "output_channels",
    "input_channels",
    "handle_mode",
    "handle_input_size",
    "pad",
    "resize",
    "memory_usage",
    "inference_speed",
    "gradual_unfreeze",
    "freeze_layers",
    "param_groups",
    "final_activation",
    "final_output_channels",
    "custom_target_size",
    "variable_depth",
    "variable_input",
    "custom_params",
    "custom_normalization",
    "custom_size",
    "custom_channels",
    "custom_config",
    "custom_batch_size",
    "custom_dilations",
    "custom_dropout",
    "custom_channels_per_block",
    "custom_channels_tracking",
    "custom_skip_configurations",
    "custom_transform",
    "custom_loss",
    "custom_metric",
    "custom_logger",
    "custom_env",
    "custom_schema",
    "custom_split",
    "custom_override",
    "custom_factory",
    "custom_registry",
    "custom_component",
    "custom_hybrid",
    "custom_import_compat",
    "custom_reproducibility",
    "custom_precision",
    "custom_recall",
    "custom_f1_score",
    "custom_iou_score",
    "custom_visualize",
    "custom_save",
    "custom_load",
    "custom_checkpoint",
    "custom_activation",
    "custom_optimizer",
    "custom_scheduler",
    "custom_batch",
    "custom_epoch",
    "custom_summary",
    "custom_grad",
    "custom_dropout",
    "custom_skip_connection",
    "custom_channel",
    "custom_init",
    "custom_init_type_mismatch",
    "custom_init_with_activation",
    "custom_forward_shape",
    "custom_output_shape",
    "custom_output_norm",
    "custom_output_channels",
    "custom_input_channels",
    "custom_handle_mode",
    "custom_handle_input_size",
    "custom_pad",
    "custom_resize",
    "custom_memory_usage",
    "custom_inference_speed",
    "custom_gradual_unfreeze",
    "custom_freeze_layers",
    "custom_param_groups",
    "custom_final_activation",
    "custom_final_output_channels",
    "custom_custom_target_size",
    "custom_custom_variable_depth",
    "custom_custom_variable_input",
    "custom_custom_params",
    "custom_custom_normalization",
    "custom_custom_size",
    "custom_custom_channels",
    "custom_custom_config",
    "custom_custom_batch_size",
    "custom_custom_dilations",
    "custom_custom_dropout",
    "custom_custom_channels_per_block",
    "custom_custom_channels_tracking",
    "custom_custom_skip_configurations",
    "custom_custom_transform",
    "custom_custom_loss",
    "custom_custom_metric",
    "custom_custom_logger",
    "custom_custom_env",
    "custom_custom_schema",
    "custom_custom_split",
    "custom_custom_override",
    "custom_custom_factory",
    "custom_custom_registry",
    "custom_custom_component",
    "custom_custom_hybrid",
    "custom_custom_import_compat",
    "custom_custom_reproducibility",
    "custom_custom_precision",
    "custom_custom_recall",
    "custom_custom_f1_score",
    "custom_custom_iou_score",
    "custom_custom_visualize",
    "custom_custom_save",
    "custom_custom_load",
    "custom_custom_checkpoint",
    "custom_custom_activation",
    "custom_custom_optimizer",
    "custom_custom_scheduler",
    "custom_custom_batch",
    "custom_custom_epoch",
    "custom_custom_summary",
    "custom_custom_grad",
    "custom_custom_dropout",
    "custom_custom_skip_connection",
    "custom_custom_channel",
    "custom_custom_init",
    "custom_custom_init_type_mismatch",
    "custom_custom_init_with_activation",
    "custom_custom_forward_shape",
    "custom_custom_output_shape",
    "custom_custom_output_norm",
    "custom_custom_output_channels",
    "custom_custom_input_channels",
    "custom_custom_handle_mode",
    "custom_custom_handle_input_size",
    "custom_custom_pad",
    "custom_custom_resize",
    "custom_custom_memory_usage",
    "custom_custom_inference_speed",
    "custom_custom_gradual_unfreeze",
    "custom_custom_freeze_layers",
    "custom_custom_param_groups",
    "custom_custom_final_activation",
    "custom_custom_final_output_channels",
    "custom_custom_custom_target_size",
    "custom_custom_custom_variable_depth",
    "custom_custom_custom_variable_input",
    "custom_custom_custom_params",
    "custom_custom_custom_normalization",
    "custom_custom_custom_size",
    "custom_custom_custom_channels",
    "custom_custom_custom_config",
    "custom_custom_custom_batch_size",
    "custom_custom_custom_dilations",
    "custom_custom_custom_dropout",
    "custom_custom_custom_channels_per_block",
    "custom_custom_custom_channels_tracking",
    "custom_custom_custom_skip_configurations",
    "custom_custom_custom_transform",
    "custom_custom_custom_loss",
    "custom_custom_custom_metric",
    "custom_custom_custom_logger",
    "custom_custom_custom_env",
    "custom_custom_custom_schema",
    "custom_custom_custom_split",
    "custom_custom_custom_override",
    "custom_custom_custom_factory",
    "custom_custom_custom_registry",
    "custom_custom_custom_component",
    "custom_custom_custom_hybrid",
    "custom_custom_custom_import_compat",
    "custom_custom_custom_reproducibility",
    "custom_custom_custom_precision",
    "custom_custom_custom_recall",
    "custom_custom_custom_f1_score",
    "custom_custom_custom_iou_score",
    "custom_custom_custom_visualize",
    "custom_custom_custom_save",
    "custom_custom_custom_load",
    "custom_custom_custom_checkpoint",
    "custom_custom_custom_activation",
    "custom_custom_custom_optimizer",
    "custom_custom_custom_scheduler",
    "custom_custom_custom_batch",
    "custom_custom_custom_epoch",
    "custom_custom_custom_summary",
    "custom_custom_custom_grad",
    "custom_custom_custom_dropout",
    "custom_custom_custom_skip_connection",
    "custom_custom_custom_channel",
    "custom_custom_custom_init",
    "custom_custom_custom_init_type_mismatch",
    "custom_custom_custom_init_with_activation",
    "custom_custom_custom_forward_shape",
    "custom_custom_custom_output_shape",
    "custom_custom_custom_output_norm",
    "custom_custom_custom_output_channels",
    "custom_custom_custom_input_channels",
    "custom_custom_custom_handle_mode",
    "custom_custom_custom_handle_input_size",
    "custom_custom_custom_pad",
    "custom_custom_custom_resize",
    "custom_custom_custom_memory_usage",
    "custom_custom_custom_inference_speed",
    "custom_custom_custom_gradual_unfreeze",
    "custom_custom_custom_freeze_layers",
    "custom_custom_custom_param_groups",
    "custom_custom_custom_final_activation",
    "custom_custom_custom_final_output_channels",
    "custom_custom_custom_custom_target_size",
    "custom_custom_custom_custom_variable_depth",
    "custom_custom_custom_custom_variable_input",
    "custom_custom_custom_custom_params",
    "custom_custom_custom_custom_normalization",
    "custom_custom_custom_custom_size",
    "custom_custom_custom_custom_channels",
    "custom_custom_custom_custom_config",
    "custom_custom_custom_custom_batch_size",
    "custom_custom_custom_custom_dilations",
    "custom_custom_custom_custom_dropout",
    "custom_custom_custom_custom_channels_per_block",
    "custom_custom_custom_custom_channels_tracking",
    "custom_custom_custom_custom_skip_configurations",
    "custom_custom_custom_custom_transform",
    "custom_custom_custom_custom_loss",
    "custom_custom_custom_custom_metric",
    "custom_custom_custom_custom_logger",
    "custom_custom_custom_custom_env",
    "custom_custom_custom_custom_schema",
    "custom_custom_custom_custom_split",
    "custom_custom_custom_custom_override",
    "custom_custom_custom_custom_factory",
    "custom_custom_custom_custom_registry",
    "custom_custom_custom_custom_component",
    "custom_custom_custom_custom_hybrid",
    "custom_custom_custom_custom_import_compat",
    "custom_custom_custom_custom_reproducibility",
    "custom_custom_custom_custom_precision",
    "custom_custom_custom_custom_recall",
    "custom_custom_custom_custom_f1_score",
    "custom_custom_custom_custom_iou_score",
    "custom_custom_custom_custom_visualize",
    "custom_custom_custom_custom_save",
    "custom_custom_custom_custom_load",
    "custom_custom_custom_custom_checkpoint",
    "custom_custom_custom_custom_activation",
    "custom_custom_custom_custom_optimizer",
    "custom_custom_custom_custom_scheduler",
    "custom_custom_custom_custom_batch",
    "custom_custom_custom_custom_epoch",
    "custom_custom_custom_custom_summary",
    "custom_custom_custom_custom_grad",
    "custom_custom_custom_custom_dropout",
    "custom_custom_custom_custom_skip_connection",
    "custom_custom_custom_custom_channel",
    "custom_custom_custom_custom_init",
    "custom_custom_custom_custom_init_type_mismatch",
    "custom_custom_custom_custom_init_with_activation",
    "custom_custom_custom_custom_forward_shape",
    "custom_custom_custom_custom_output_shape",
    "custom_custom_custom_custom_output_norm",
    "custom_custom_custom_custom_output_channels",
    "custom_custom_custom_custom_input_channels",
    "custom_custom_custom_custom_handle_mode",
    "custom_custom_custom_custom_handle_input_size",
    "custom_custom_custom_custom_pad",
    "custom_custom_custom_custom_resize",
    "custom_custom_custom_custom_memory_usage",
    "custom_custom_custom_custom_inference_speed",
    "custom_custom_custom_custom_gradual_unfreeze",
    "custom_custom_custom_custom_freeze_layers",
    "custom_custom_custom_custom_param_groups",
    "custom_custom_custom_custom_final_activation",
    "custom_custom_custom_custom_final_output_channels",
    "custom_custom_custom_custom_custom_target_size",
    "custom_custom_custom_custom_variable_depth",
    "custom_custom_custom_custom_variable_input",
    "custom_custom_custom_custom_custom_params",
    "custom_custom_custom_custom_custom_normalization",
    "custom_custom_custom_custom_custom_size",
    "custom_custom_custom_custom_custom_channels",
    "custom_custom_custom_custom_custom_config",
    "custom_custom_custom_custom_custom_batch_size",
    "custom_custom_custom_custom_custom_dilations",
    "custom_custom_custom_custom_custom_dropout",
    "custom_custom_custom_custom_custom_channels_per_block",
    "custom_custom_custom_custom_custom_channels_tracking",
    "custom_custom_custom_custom_custom_skip_configurations",
    "custom_custom_custom_custom_custom_transform",
    "custom_custom_custom_custom_custom_loss",
    "custom_custom_custom_custom_custom_metric",
    "custom_custom_custom_custom_custom_logger",
    "custom_custom_custom_custom_custom_env",
    "custom_custom_custom_custom_custom_schema",
    "custom_custom_custom_custom_custom_split",
    "custom_custom_custom_custom_custom_override",
    "custom_custom_custom_custom_custom_factory",
    "custom_custom_custom_custom_custom_registry",
    "custom_custom_custom_custom_custom_component",
    "custom_custom_custom_custom_custom_hybrid",
    "custom_custom_custom_custom_custom_import_compat",
    "custom_custom_custom_custom_custom_reproducibility",
    "custom_custom_custom_custom_custom_precision",
    "custom_custom_custom_custom_custom_recall",
    "custom_custom_custom_custom_custom_f1_score",
    "custom_custom_custom_custom_custom_iou_score",
    "custom_custom_custom_custom_custom_visualize",
    "custom_custom_custom_custom_custom_save",
    "custom_custom_custom_custom_custom_load",
    "custom_custom_custom_custom_custom_checkpoint",
    "custom_custom_custom_custom_custom_activation",
    "custom_custom_custom_custom_custom_optimizer",
    "custom_custom_custom_custom_custom_scheduler",
    "custom_custom_custom_custom_custom_batch",
    "custom_custom_custom_custom_custom_epoch",
    "custom_custom_custom_custom_custom_summary",
    "custom_custom_custom_custom_custom_grad",
    "custom_custom_custom_custom_custom_dropout",
    "custom_custom_custom_custom_custom_skip_connection",
    "custom_custom_custom_custom_custom_channel",
    "custom_custom_custom_custom_custom_init",
    "custom_custom_custom_custom_custom_init_type_mismatch",
    "custom_custom_custom_custom_custom_init_with_activation",
    "custom_custom_custom_custom_custom_forward_shape",
    "custom_custom_custom_custom_custom_output_shape",
    "custom_custom_custom_custom_custom_output_norm",
    "custom_custom_custom_custom_custom_output_channels",
    "custom_custom_custom_custom_custom_input_channels",
    "custom_custom_custom_custom_custom_handle_mode",
    "custom_custom_custom_custom_custom_handle_input_size",
    "custom_custom_custom_custom_custom_pad",
    "custom_custom_custom_custom_custom_resize",
    "custom_custom_custom_custom_custom_memory_usage",
    "custom_custom_custom_custom_custom_inference_speed",
    "custom_custom_custom_custom_custom_gradual_unfreeze",
    "custom_custom_custom_custom_custom_freeze_layers",
    "custom_custom_custom_custom_custom_param_groups",
    "custom_custom_custom_custom_custom_final_activation",
    "custom_custom_custom_custom_custom_final_output_channels",
]

# Leer tests lentos para marcarlos como critical
slow_tests = set()
try:
    with open(SLOW_TESTS_PATH, encoding="utf-8") as f:
        for line in f:
            if (
                line.startswith("#")
                or line.startswith("Duration")
                or not line.strip()
            ):
                continue
            _, classname, name = line.strip().split("\t")
            slow_tests.add((classname, name))
except FileNotFoundError:
    pass


def assign_priority(row):
    test_name = row[idx_name].lower()
    file_path = row[idx_file].lower()
    # Critical si es test lento o contiene palabra clave critical
    if (row[idx_class], row[idx_name]) in slow_tests:
        return "critical"
    if any(kw in test_name or kw in file_path for kw in CRITICAL_KEYWORDS):
        return "critical"
    if any(kw in test_name or kw in file_path for kw in HIGH_KEYWORDS):
        return "high"
    if (
        "util" in test_name
        or "helper" in test_name
        or "validation" in test_name
    ):
        return "medium"
    return "low"


with open(CSV_PATH, newline="", encoding="utf-8") as f:
    reader = list(csv.reader(f))
    explanation = reader[0]
    header = reader[1]
    data = reader[2:]

# Documentar el criterio en la explicación
explanation = "# Priority assigned as: critical (pipeline, training, "
explanation += "evaluation, slowest tests), high (core components), "
explanation += "medium (utils/helpers), low (accessory). See script for "
explanation += "details."

# Añadir columna si no existe
if "Priority" not in header:
    header.append("Priority")
    add_priority = True
else:
    add_priority = False
    idx_priority = header.index("Priority")

idx_file = header.index("File Path")
idx_name = header.index("Test Name")
idx_class = header.index("File Path")

updated = [explanation, header]
for row in data:
    priority = assign_priority(row)
    if add_priority:
        row.append(priority)
    else:
        row[idx_priority] = priority
    updated.append(row)

with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(updated)
