# @package _global_

# Base configuration applied to all experiments unless overridden.
# This file centralizes common settings and serves as the main configuration.

defaults:
  - training: default
  - model: default
  - data: default
  - data/transform: augmentations
  - data/dataloader: default
  - evaluation: default
  - _self_

# General project settings
project_name: "crack-segmentation"
output_dir: artifacts/                # Default directory for all outputs
data_dir: data/               # Default directory for datasets

# Seed for reproducibility. A specific seed ensures that any randomness
# in the model initialization, data shuffling, or augmentations is consistent
# across runs.
random_seed: 42

# Experiment configuration
experiment:
  name: "main_experiment"
  output_dir: "artifacts/experiments"

# Logging configuration
log_level: "INFO"
log_to_file: true

# Device configuration
require_cuda: false        # Allow CPU execution for testing
device: "auto"            # Auto-select device (GPU if available, CPU otherwise)

# Pre-declare model node to allow command-line overrides
model: {}

timestamp_parsing:
  min_parts: 2
  date_len: 8
  time_len: 6

thresholds:
  default: 0.5
  metric: 0.5
  loss_weight: 0.5
  gamma: 0.5

visualization:
  num_cols: 3
  num_cols_no_targets: 2

# Hydra configuration
hydra:
  run:
    dir: artifacts/experiments/${now:%Y%m%d-%H%M%S}-${experiment.name}
  sweep:
    dir: artifacts/experiments/multirun/${now:%Y%m%d-%H%M%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false