# @package _global_

# Base configuration applied to all experiments unless overridden.
# This file centralizes common settings.

defaults:
  - _self_
  - training: default
  - model: default
  - data: default
  - data/transform: augmentations
  - data/dataloader: default
  - evaluation: default
  - optional local: local # for local overrides

# General project settings
project_name: "crack-segmentation"
output_dir: artifacts/outputs/        # Default directory for all outputs
data_dir: data/               # Default directory for datasets

# Seed for reproducibility. A specific seed ensures that any randomness
# in the model initialization, data shuffling, or augmentations is consistent
# across runs.
seed: 42

timestamp_parsing:
  min_parts: 2
  date_len: 8
  time_len: 6

thresholds:
  default: 0.5
  metric: 0.5
  loss_weight: 0.5
  gamma: 0.5

visualization:
  num_cols: 3
  num_cols_no_targets: 2

# Hydra configuration
hydra:
  run:
    dir: artifacts/outputs/${now:%Y%m%d-%H%M%S}
  job:
    chdir: false