# @package _global_

# Base configuration applied to all experiments unless overridden.
# This file centralizes common settings and serves as the main configuration.

defaults:
  - training: default
  - model: default
  - data: default  # Restore data config but experiments can override it
  - data/transform: augmentations
  - data/dataloader: default
  - evaluation: default
  - _self_

# General project settings
project_name: "crack-segmentation"
output_dir: artifacts/                # Default directory for all outputs
data_dir: data/               # Default directory for datasets

# Seed for reproducibility. A specific seed ensures that any randomness
# in the model initialization, data shuffling, or augmentations is consistent
# across runs.
random_seed: 42
seed: 42  # Alias for compatibility

# Experiment configuration
experiment:
  # name: "experiment"  # Removed to avoid conflicts with specific experiment names
  output_dir: "artifacts/experiments"

# Logging configuration
log_level: "INFO"
log_to_file: true

# Device configuration
require_cuda: false        # Allow CPU execution for testing
device: "auto"            # Auto-select device (GPU if available, CPU otherwise)

# Pre-declare model node to allow command-line overrides
model: {}

# Memory optimization settings (default values)
memory:
  gradient_checkpointing: false
  empty_cache_freq: 100
  monitor_memory: false

# Hardware-specific optimizations (default values)
hardware:
  cudnn_benchmark: true
  cudnn_deterministic: false
  mixed_precision: false
  memory_efficient_attention: false

timestamp_parsing:
  min_parts: 2
  date_len: 8
  time_len: 6

thresholds:
  default: 0.5
  metric: 0.5
  loss_weight: 0.5
  gamma: 0.5

visualization:
  num_cols: 3
  num_cols_no_targets: 2

# Hydra configuration
# Modified to prevent duplicate folder creation - Project uses its own ExperimentManager
hydra:
  output_subdir: null  # Disable .hydra subdirectory creation
  job:
    chdir: false       # Don't change working directory
  run:
    dir: .            # Use current directory (project handles output dirs)