# Main Hydra configuration for experiment runner

defaults:
  - base
  - data: default
  - data/transform: augmentations
  - data/dataloader: default
  - model: default
  - training: default
  - evaluation: default
  - _self_

# General configuration
random_seed: 42
require_cuda: true
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_to_file: true

# Experiment configuration
experiment:
  name: "crackseg"
  output_dir: "outputs"

# Configure Hydra to use the same directory structure as ExperimentManager
hydra:
  run:
    dir: outputs/experiments/${now:%Y%m%d-%H%M%S}-${hydra.job.name}
  sweep:
    dir: outputs/multirun/${now:%Y%m%d-%H%M%S}
    subdir: ${hydra.job.num}
  job:
    # Don't change the working directory
    chdir: false

# Data configuration
data:
  root_dir: "data"
  train_dir: "${data.root_dir}/train"
  val_dir: "${data.root_dir}/val"
  test_dir: "${data.root_dir}/test"
  batch_size: 16
  num_workers: 4
  pin_memory: true

# Model configuration - This entire section will be loaded via defaults
# model:
#   name: "unet"
#   encoder:
#     backbone: "resnet34"
#     pretrained: true
#     input_channels: 3
#   bottleneck:
#     type: "simple"
#   decoder:
#     type: "unet"
#     use_attention: true

# Training configuration - This entire section will be loaded via defaults
# training:
#   num_epochs: 100
#   optimizer:
#     type: "adam"
#     lr: 0.001
#     weight_decay: 0.0001
#   scheduler:
#     type: "reduce_on_plateau"
#     patience: 5
#     factor: 0.5
#   loss:
#     type: "bce_dice"
#     dice_weight: 0.5
#   early_stopping:
#     enabled: true
#     patience: 10
#     min_delta: 0.001
#   amp_enabled: true  # Automatic Mixed Precision
#   checkpoints:
#     save_freq: 5  # Save every N epochs
#     checkpoint_dir: "checkpoints"
#     save_best:
#       enabled: true
#       monitor_metric: "val_dice"
#       monitor_mode: "max"  # or "min" for losses

# Evaluation configuration - This entire section will be loaded via defaults
# evaluation:
#   metrics:
#     iou: {}
#     dice: {}
#     precision: {}
#     recall: {}
#     accuracy: {}
