# config/training/loss/bce_dice.yaml
# BCE + Dice Loss Configuration
_target_: src.training.losses.BCEDiceLoss
config:
  _target_: src.training.losses.bce_dice_loss.BCEDiceLossConfig
  bce_weight: ${thresholds.loss_weight}
  dice_weight: ${thresholds.loss_weight}
  dice_smooth: 1.0
  dice_sigmoid: true
  dice_eps: 1e-6
  bce_reduction: mean
  bce_pos_weight: null  # Optional positive class weight for BCE