# config/training/loss/combined.yaml
# Example Combined Loss: Focal + Dice
_target_: src.training.losses.CombinedLoss  # Combined loss class (multiple losses)
losses:
  - config:
      _target_: src.training.losses.FocalLoss  # Focal loss component
      alpha: 0.5   # Weighting factor for rare class
      gamma: 2.0   # Focusing parameter
      sigmoid: True
    weight: 0.6    # Weight for Focal loss in total loss
  - config:
      _target_: src.training.losses.DiceLoss   # Dice loss component
      smooth: 1.0
      sigmoid: True  # Note: Sigmoid might be applied twice if not handled in CombinedLoss
    weight: 0.4    # Weight for Dice loss in total loss 