"""LaTeX templates for experiment reports.

This module provides professional LaTeX templates for generating
academic-quality experiment reports suitable for publications.
"""

from abc import ABC, abstractmethod


class BaseLaTeXTemplate(ABC):
    """Base class for LaTeX templates."""

    @abstractmethod
    def get_template_content(self) -> str:
        """Get template content."""
        pass

    def get_preamble(self) -> str:
        """Get LaTeX preamble with packages and settings."""
        return r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{array}
\usepackage{longtable}
\usepackage{float}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{listings}
\usepackage{color}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{makecell}
\usepackage{siunitx}
\usepackage{pgfplots}
\usepackage{tikz}

% Page geometry
\geometry{margin=2.5cm}

% Hyperref setup
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    citecolor=red
}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\rhead{CrackSeg Experiment Report}
\lhead{\leftmark}
\rfoot{\thepage}

% Title formatting
\titleformat{\section}{\Large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{1em}{}

% Code listing setup
\lstset{
    basicstyle=\ttfamily\footnotesize,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
    stepnumber=1,
    numbersep=5pt,
    backgroundcolor=\color{gray!10},
    commentstyle=\color{green!60!black},
    keywordstyle=\color{blue},
    stringstyle=\color{red}
}

% Custom colors
\definecolor{metriccolor}{RGB}{52, 152, 219}
\definecolor{successcolor}{RGB}{39, 174, 96}
\definecolor{warningcolor}{RGB}{243, 156, 18}
\definecolor{errorcolor}{RGB}{231, 76, 60}

% Custom commands
\newcommand{\metric}[2]{\textcolor{metriccolor}{\textbf{#1}: #2}}
\newcommand{\success}[1]{\textcolor{successcolor}{#1}}
\newcommand{\warning}[1]{\textcolor{warningcolor}{#1}}
\newcommand{\error}[1]{\textcolor{errorcolor}{#1}}
\newcommand{\experimentid}[1]{\texttt{#1}}
\newcommand{\code}[1]{\lstinline{#1}}

% Table setup
\newcolumntype{P}[1]{>{\centering\arraybackslash}p{#1}}
\newcolumntype{M}[1]{>{\centering\arraybackslash}m{#1}}

% Document info
\author{CrackSeg Experimental Reporting System}
\date{\today}
"""


class LaTeXExecutiveSummaryTemplate(BaseLaTeXTemplate):
    """Executive summary LaTeX template."""

    def get_template_content(self) -> str:
        """Get executive summary LaTeX template content."""
        return (
            self.get_preamble()
            + r"""
\begin{document}

\title{\textbf{{{title}}}}
\maketitle

\begin{abstract}
This report provides an executive summary of the crack segmentation experiment
{{experiment_id}}. The experiment was conducted using the CrackSeg framework
and generated on {{generation_timestamp}}.
\end{abstract}

\section{Executive Summary}

{{executive_summary}}

\section{Key Findings}

{{key_findings}}

\section{Performance Overview}

{{performance_metrics}}

\section{Recommendations}

{{recommendations}}

\section{Experiment Details}

\begin{table}[h]
\centering
\begin{tabular}{ll}
\toprule
\textbf{Parameter} & \textbf{Value} \\
\midrule
Experiment ID & \experimentid{{{experiment_id}}} \\
Experiment Name & {{experiment_name}} \\
Status & {{status}} \\
Duration & {{duration}} \\
\bottomrule
\end{tabular}
\caption{Experiment Information}
\label{tab:experiment_info}
\end{table}

\section{Full Report}

For detailed technical analysis, please refer to the complete technical report.

\vspace{2cm}

\begin{center}
\rule{0.4\textwidth}{0.4pt}

\textit{Report generated by CrackSeg Experimental Reporting System}

\small{Generated on {{generation_timestamp}}}
\end{center}

\end{document}
"""
        )


class LaTeXPublicationTemplate(BaseLaTeXTemplate):
    """Publication-ready LaTeX template."""

    def get_template_content(self) -> str:
        """Get publication-ready LaTeX template content."""
        return (
            self.get_preamble()
            + r"""
\begin{document}

\title{\textbf{{{title}}}}
\maketitle

\begin{abstract}
{{abstract}}
\end{abstract}

\section{Introduction}

{{introduction}}

\section{Methodology}

\subsection{Model Architecture}

{{model_architecture}}

\subsection{Training Configuration}

{{training_config}}

\subsection{Dataset}

{{dataset_description}}

\section{Results}

\subsection{Performance Metrics}

{{performance_metrics}}

\subsection{Training Analysis}

{{training_curves}}

\subsection{Comparative Analysis}

{{comparison_results}}

\section{Discussion}

{{discussion}}

\section{Conclusions}

{{conclusions}}

\section{Future Work}

{{future_work}}

\section{References}

{{references}}

\appendix

\section{Experimental Setup}

{{experimental_setup}}

\section{Detailed Results}

{{detailed_results}}

\section{Figures}

{{publication_figures}}

\end{document}
"""
        )


class LaTeXTechnicalTemplate(BaseLaTeXTemplate):
    """Technical detailed LaTeX template."""

    def get_template_content(self) -> str:
        """Get technical detailed LaTeX template content."""
        return (
            self.get_preamble()
            + r"""
\begin{document}

\title{\textbf{{{title}}}}
\maketitle

\begin{abstract}
This technical report provides a comprehensive analysis of the crack
segmentation experiment {{experiment_id}}. The report includes detailed
performance metrics, training analysis, and technical recommendations.
\end{abstract}

\section{Experiment Information}

\begin{table}[h]
\centering
\begin{tabular}{ll}
\toprule
\textbf{Parameter} & \textbf{Value} \\
\midrule
Experiment ID & \experimentid{{{experiment_id}}} \\
Experiment Name & {{experiment_name}} \\
Configuration & {{config_summary}} \\
Duration & {{duration}} \\
Status & {{status}} \\
\bottomrule
\end{tabular}
\caption{Experiment Information}
\label{tab:experiment_info}
\end{table}

\section{Executive Summary}

{{executive_summary}}

\section{Performance Analysis}

\subsection{Key Metrics}

{{performance_metrics}}

\subsection{Training Curves}

{{training_curves}}

\subsection{Detailed Analysis}

{{technical_details}}

\section{Technical Details}

\subsection{Model Architecture}

{{model_architecture}}

\subsection{Training Configuration}

{{training_config}}

\subsection{Data Configuration}

{{data_config}}

\section{Results Analysis}

{{results_analysis}}

\section{Recommendations}

{{recommendations}}

\section{Artifacts}

{{artifacts}}

\section{Metadata}

{{metadata}}

\vspace{2cm}

\begin{center}
\rule{0.4\textwidth}{0.4pt}

\textit{Generated by CrackSeg Experimental Reporting System}

\small{Generated on {{generation_timestamp}}}
\end{center}

\end{document}
"""
        )


def get_template_class(template_name: str) -> type[BaseLaTeXTemplate]:
    """Get template class by name.

    Args:
        template_name: Name of the template class.

    Returns:
        Template class.

    Raises:
        ValueError: If template class is not found.
    """
    template_classes = {
        "LaTeXExecutiveSummaryTemplate": LaTeXExecutiveSummaryTemplate,
        "LaTeXPublicationTemplate": LaTeXPublicationTemplate,
        "LaTeXTechnicalTemplate": LaTeXTechnicalTemplate,
    }

    if template_name not in template_classes:
        raise ValueError(f"Template class not found: {template_name}")

    return template_classes[template_name]
