name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: crackseg
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material mkdocs-macros-plugin

      - name: Build and Deploy Documentation
        run: |
          mkdocs gh-deploy --force --clean